DROP TABLE IF EXISTS COUNTRY;

CREATE TABLE country (
  name VARCHAR(250) NOT NULL,
  capital VARCHAR(250) NOT NULL,
  code VARCHAR(250) NOT NULL,
  flag VARCHAR(250) NOT NULL,
  region VARCHAR(250) NOT NULL
);